config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :installs
  resources :categories do
    resources :products do
      resources :reviews
    end
  end
  resources :users
    match 'users/show', to: 'users#show', via: 'get'

  root to: 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_uniqueness_of :name
  has_many :products
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_format_of :price, :with => /\A\d+(?:\.\d{0,2})?\z/
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :price
  belongs_to :category
  belongs_to :user
  has_many :reviews
  has_many :ratings

  def average_rating
  	reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates_presence_of :user_id
  validates_presence_of :content
  validates_presence_of :rating
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname
  validates_presence_of :firstname
  validates_presence_of :lastname
  has_many :reviews
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :firstname, :lastname) }
        end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
    if !current_user.try(:admin?)
      redirect_to(new_user_session_path)
    end
  end

  def edit
    if !current_user.try(:admin?)
      redirect_to(new_user_session_path)
    end
  end

  def create
    if current_user.try(:admin?)
      self.category = Category.new(category_params)

      if category.save
        redirect_to category, notice: 'Category was successfully created.'
      else
        render action: 'new'
      end
    else
      redirect_to(new_user_session_path)
    end
  end

  def update
    if current_user.try(:admin?)
      if category.update(category_params)
        redirect_to category, notice: 'Category was successfully updated.'
      else
        render action: 'edit'
      end
    else
      redirect_to(new_user_session_path)
    end
  end

  def destroy
    if
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)
  before_filter :authenticate_user!
  def index
  end

  def show
  end

  def new
  end

  def edit
    if user_signed_in?
      if current_user.id != product.user_id
        redirect_to category_product_url(category, product), flash: {error: "You are not allowed to edit this product." }
      end
    else
      redirect_to(new_user_session_path)      
    end
  end

  def create
    if user_signed_in?
      self.product = Product.new(product_params)
      if product.save
        category.products << product
        redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
      else
        render action: 'new'
      end
    else
      redirect_to(new_user_session_path)
    end
  end

  def update
    if user_signed_in?
      if current_user.id == product.user_id
        if self.product.update(product_params)
        redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
        else
        render action: 'edit'
        end
      else
        redirect_to category_product_url(category, product), flash: {error: "You are not allowed to edit this product." }
      end
    else
      redirect_to(new_user_session_path)
    end
  end

  # DELETE /products/1
  def destroy
    if user_signed_in?
      if current_user.id == product.user_id || current_user.try(:admin?)
        product.destroy
        redirect_to category_url(product.category)
      else
        redirect_to category_product_url(category, product), error: "You are not allowed to edit this product."
      end
    else
      redirect_to(new_user_session_path)
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)
  before_filter :authenticate_user!
  def index
    @reviews = Review.all
  end

  def new
  end

  def edit
  end

  def create
    self.review = Review.new(review_params)

    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  def show
    @review = Review.find(:id => params[:id])
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
expose(:review)
expose(:product)
	def new
  	end

	def show
	  @user = User.find(params[:id])
	  @review = Review.order("created_at DESC").limit(5).where(:user_id => @user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category
\|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
%h1 Categories

%table.table
  - categories.each do |category|
    %tr
      %td= category.name
      %td
        %span= image_tag "Shopping-cart-1@1x.png"
        = link_to 'Show Products', category
      -if current_user.try(:admin?)
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%br
-if current_user.try(:admin?)
  = link_to 'New Category', new_category_path, :class => "new-cat"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
%p#notice= notice
.col-sm-8
  %h1.category-name
    %b= category.name
    Products: 

  %p
    - category.products.each do |product|
      %p
        %span.present= image_tag("Present-1@1x.png")
        = link_to product.title, category_product_path(product.category, product), :class => "product-list-title"
.col-sm-4
  %p
    %h3 Add New Product
    = render 'products/form'
  -if current_user.try(:admin?)
    = link_to 'Edit Category', edit_category_path(category)
    %br
    %br
    = link_to 'Edit Products From This Category', category_products_path(category.id), :class => "new-cat"
    
= link_to 'Back', categories_path, class: 'btn btn-default back'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato:300,400,700,400italic'
    = javascript_include_tag 'application'
    %title Netguru Workshops 2014

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          = link_to 'Home', root_path 
          %span= image_tag "Ring@2x.png"
          %span Netguru Warsaw Workshops 2014
          
        %p.navbar-text.navbar-right
          -if user_signed_in?
            -if current_user.admin == true
              %span Admin
            %span Welcome
            = link_to current_user.firstname, user_path(current_user)
            = link_to 'Sign Out', destroy_user_session_path, :method => :delete
          -else
            %span Welcome, please 
            = link_to 'Sign In', new_user_session_path
            %span or
            = link_to 'Register', new_user_registration_path
    .container
      .main-content
        .row
          .col-lg-12
          - if notice
            %p.alert.alert-success= notice
          - elsif alert
            %p.alert.alert-danger= alert
          
          = yield

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation
      %h2= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg
  -if user_signed_in?
    = f.hidden_field :user_id, class: 'form-control', value: current_user.id
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :description
      = f.text_area :description, class: 'form-control'
    .form-group
      = f.label :price
      = f.text_field :price, class: 'form-control'
      %br
      = f.submit 'Save', class: 'btn btn-default'
  -else
    %p 
      You have to 
      =link_to 'sign in', new_user_session_path
      to create a product

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', category_product_path(category, product)
\|
= link_to 'Back', category_path(category)

app/views/products/index.html.haml
%h1
  Products From
  =category.name


%table.table
  %tr
    %th Title
    %th Description
    %th Price
    %th
    %th
    %th

  - products.each do |product|
    -if product.category_id == category.id
      %tr
        %td= product.title
        %td= product.description
        %td= product.price
        %td= link_to 'Show', category_product_path(product.category, product)
        %td= link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'Back', category_path(category), class: 'btn btn-primary'

app/views/products/new.html.haml
%h1 Add New Product

= render 'form'

= link_to 'Back', category_products_path

app/views/products/show.html.haml
%p#notice= notice
%p#error= flash[:error]

.col-sm-8
  %p.product-title
    %b= product.title
  %p.product-desc
    %b Description:
    %br
    = product.description
  %p.product-price
    %span= image_tag "Dollar-coin@1x.png"
    %b Price:
    = product.price
  %p.product-category
    %span= image_tag "Tag-1@1x.png"
    %b Category
    = product.category.name
-if current_user.id != product.user_id
  .col-sm-4
    %h4 Submit a review
    = render 'reviews/form'
-else
  = link_to 'Edit', edit_category_product_path(category.id, product.id), class: 'btn btn-default'
%br
%h3 Reviews
= render reviews
%br
= link_to 'Back', category_path(category), class: 'btn btn-default'

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %h2= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :content, class: 'label-review'
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.input :rating, collection: 1..5, class: 'form-control rating'
    = f.hidden_field :user_id, class: 'form-control', value: current_user.id

  = f.submit 'Save', class: 'btn btn-default'

app/views/reviews/_review.html.haml
.rev-cont
  %p= review.content
  %p.rev-rating
    Rating: 
    %b= review.rating
    %br
    %em
      Author:
      = review.author

app/views/reviews/index.html.haml
%h1
  Reviews For
  =product.title


%table.table
  %tr
    %th Content
    %th Rating
    %th Action

  - @reviews.each do |review|
    -if review.product_id == product.id
      %tr
        %td= review.content
        %td= review.rating
        %td= link_to 'Show', category_product_path(product.category, product)

%br
//= link_to 'Back', , class: 'btn btn-primary'

app/views/reviews/new.html.haml
new.html.haml

app/views/users/show.html.haml
.col-sm-4
  %h2.product-title User Profile
  %b.user-col
    %h3
      =@user.firstname
      =@user.lastname
      =image_tag("User-Round@1x.png")
    %br
  %p 
    E-mail adress:
    =@user.email
  %p
    User Since:
    =@user.created_at.to_formatted_s(:short)
  %p
    Last Activity:
    =@user.last_sign_in_at.to_formatted_s(:short)
  -if current_user.try(:admin?)
    %p This is an admin account

.col-sm-8
  %h2 Latest Reviews
  - @review.each do |rev|
    .rev-cont
      %p= rev.content
      %p.rev-rating
        Rating: 
        %b= rev.rating
        %p
          Date:
          = rev.created_at.to_formatted_s(:short)